name: Deploy Cloudflare Workers

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  deployments: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      WORKDIR: cloudflare

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: |
            package-lock.json
            cloudflare/package-lock.json
            cloudflare/package.json

      - name: Install dependencies
        working-directory: ${{ env.WORKDIR }}
        run: npm install --no-fund --no-audit

      - name: Type check
        working-directory: ${{ env.WORKDIR }}
        run: npm run typecheck

      - name: Run tests
        working-directory: ${{ env.WORKDIR }}
        run: npm run test:run

      - name: Build (dry run)
        working-directory: ${{ env.WORKDIR }}
        run: npm run build

      - name: Deploy to Cloudflare
        if: github.ref == 'refs/heads/main'
        working-directory: ${{ env.WORKDIR }}
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
        run: npm run deploy
